
add_newline = false

[username]
style_user = "#33FFBD"
format = "[$user]($style)"
show_always = false

[hostname]
style = "#33FFBD"
format = "[@$hostname]($style) "
ssh_only = true

[directory]
style = "#005FAF"
read_only = " "

[git_branch]
symbol = " "

[aws]
symbol = "  "

[buf]
symbol = " "
format = "via [$symbol]($style)"

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "
format = "via [$symbol]($style)"

[docker_context]
symbol = " "

[dotnet]
format = "[$symbol(🎯 $tfm )]($style)"

[elixir]
symbol = " "
format = "via [$symbol]($style)"

[elm]
symbol = " "
format = "via [$symbol]($style)"

[golang]
symbol = " "
format = "via [$symbol]($style)"

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "
format = "via [$symbol]($style)"

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = "via [$symbol]($style)"

[package]
symbol = " "

[python]
symbol = " "
format = "via [$symbol]($style)"

[spack]
symbol = "🅢 "

[rust]
symbol = " "
format = "via [$symbol]($style)"

[vagrant]
format = "via [$symbol]($style)"

